# Generated by Django 6.0.8 on 2026-08-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroseconomicos',
            name='base_produccion',
            field=models.CharField(choices=[('CORTE', 'Partir del corte de agua (el petroleo se deduce)'), ('CAUDAL', 'Partir del caudal de petroleo (el corte se deduce)')], default='CORTE', help_text='El liquido total lo fijan los pozos. Elija cual de los dos valores manda; el otro se calcula para no romper el balance.', max_length=8, verbose_name='Base del perfil'),
        ),
        migrations.AlterField(
            model_name='parametroseconomicos',
            name='corte_agua_inicial',
            field=models.FloatField(default=0.7, help_text='Corte del patron antes de la primera irrupcion.', verbose_name='Corte de agua inicial (fracc.)'),
        ),
        migrations.AlterField(
            model_name='parametroseconomicos',
            name='qo_inicial',
            field=models.FloatField(default=520.0, help_text='Se usa como dato de partida en modo CAUDAL, y como respaldo cuando el proyecto todavia no tiene productores con caudal.', verbose_name='Caudal de petroleo inicial (BOPD)'),
        ),
    ]
