# Generated by Django 6.0.8 on 2026-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametroseconomicos_base_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozo',
            name='tipo_bomba_iny',
            field=models.CharField(choices=[('TRIPLEX', 'BombaTriplex'), ('QUINTUPLEX', 'Bomba Quintuplex'), ('HPS', 'HPS - sistema de bombeo horizontal'), ('NA', 'No aplica (productor)')], default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='tipo_levantamiento',
            field=models.CharField(choices=[('NAT', 'Flujo natural'), ('BES', 'Bombeo electrosumergible (BES/ESP)'), ('BH', 'Bombeo hidráulico (Jet)'), ('BM', 'Bombeo mecánico'), ('PCP', 'Bomba de cavidad progresiva (PCP)'), ('GL', 'Gas lift'), ('HPS', 'Inyección con HPS'), ('Q/T', 'Inyección con bomba reciprocante (quintuplex o triplex)')], default='BES', max_length=4),
        ),
    ]
